# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=10)),
                ('all_colors', models.TextField()),
                ('hunger', models.IntegerField(default=3)),
                ('wellness', models.IntegerField(default=5)),
                ('happiness', models.IntegerField(default=1)),
                ('adopt_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
