# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fishing_skill',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='fishing_skill_progess',
            field=models.IntegerField(default=0),
        ),
    ]
