# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180416_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fishing_rod',
            field=models.IntegerField(default=0),
        ),
    ]
