# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_fishing_rod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fishing_bait',
            field=models.IntegerField(default=0),
        ),
    ]
