# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-16 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_fishing_bait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fishing_skill_progess',
            new_name='fishing_skill_progress',
        ),
    ]
