# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180418_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_avatar',
            field=models.CharField(default='hi-im-new', max_length=140),
        ),
    ]
