# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-20 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180418_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dowsing_rod',
            field=models.IntegerField(default=0),
        ),
    ]
