# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-25 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
