# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-26 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warnings',
            field=models.TextField(blank=True, help_text='Please note the date, time, and a short description of each infraction.', null=True),
        ),
    ]
