from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^world/$", views.world_page, name="world_page"),
    re_path(r"^garden/$", views.garden_page, name="garden_page"),
    re_path(r"^garden/gather/$", views.garden_gather, name="garden_gather"),
    re_path(r"^hospital/$", views.hospital_page, name="hospital_page"),
    re_path(
        r"^hospital/appointment/$",
        views.make_hospital_appointment,
        name="make_hospital_appointment",
    ),
    re_path(
        r"^hospital/pickup/$",
        views.pickup_hospital_medicine,
        name="pickup_hospital_medicine",
    ),
    re_path(r"^pound/$", views.pound_page, name="pound_page"),
    re_path(r"^pound/release/$", views.give_up_pet, name="give_up_pet"),
    re_path(
        r"^pound/adopt/(?P<adopt>[\w-]+)$",
        views.adopt_from_pound,
        name="adopt_from_pound",
    ),
    re_path(r"^games/$", views.games_page, name="games_page"),
    re_path(r"^games/blackjack/$", views.blackjack_page, name="blackjack_page"),
    re_path(r"^games/tictactoe/$", views.tictactoe_page, name="tictactoe_page"),
    re_path(r"^games/pyramids/$", views.pyramids_page, name="pyramids_page"),
    re_path(
        r"^games/wheel/serendipity/$",
        views.wheel_serendipity_page,
        name="wheel_serendipity_page",
    ),
    re_path(r"^games/wheel/plush/$", views.wheel_plush_page, name="wheel_plush_page"),
    re_path(
        r"^games/(?P<game>[A-Za-z]+)/send/$",
        views.send_score,
        name="send_score",
    ),
    re_path(r"fishing/$", views.fishing_page, name="fishing_page"),
    re_path(r"fishing/purchase/rod/$", views.purchase_rod, name="purchase_rod"),
    re_path(r"fishing/purchase/upgrade/$", views.upgrade_rod, name="upgrade_rod"),
    re_path(r"fishing/purchase/bait/$", views.purchase_bait, name="purchase_bait"),
    re_path(r"fishing/fish/$", views.fish, name="fish"),
    re_path(r"fishing/(?P<pk>[0-9]+)/sell/$", views.sell_fish, name="sell_fish"),
    re_path(r"dump/$", views.dump_page, name="dump_page"),
    re_path(
        r"dump/(?P<pk>[0-9]+)/take/$",
        views.take_from_dump,
        name="take_from_dump",
    ),
    re_path(r"dump/add/$", views.dump_item, name="dump_item"),
    re_path(r"quarry/$", views.quarry_page, name="quarry_page"),
    re_path(
        r"quarry/purchase/rod/$",
        views.purchase_dowsing_rod,
        name="purchase_dowsing_rod",
    ),
    re_path(
        r"quarry/upgrade/rod/$",
        views.upgrade_dowsing_rod,
        name="upgrade_dowsing_rod",
    ),
    re_path(r"quarry/dowse/$", views.dowse, name="dowse"),
    re_path(
        r"quarry/trade/(?P<crystal>[\w-]+)/$",
        views.trade_crystals,
        name="trade_crystals",
    ),
    re_path(r"restricted/$", views.restricted_area_page, name="restricted_area_page"),
    re_path(
        r"restricted/update/(?P<crystal>[\w-]+)/$",
        views.update_card,
        name="update_card",
    ),
    re_path(r"restricted/activate/$", views.activate_card, name="activate_card"),
    re_path(
        r"restricted/machine/$",
        views.restricted_machine,
        name="restricted_machine",
    ),
    # DAILIES
    re_path(
        r"meatloaf/$",
        views.almighty_meatloaf_page,
        name="almighty_meatloaf_page",
    ),
    re_path(r"meatloaf/take/$", views.take_from_meatloaf, name="take_from_meatloaf"),
    re_path(r"trails/$", views.trails_page, name="trails_page"),
    re_path(r"trails/run/$", views.trails, name="trails"),
    re_path(r"orchard/$", views.apple_orchard_page, name="apple_orchard_page"),
    re_path(r"orchard/take/$", views.apple_orchard, name="apple_orchard"),
    re_path(r"day-old/$", views.day_old_stock_page, name="day_old_stock_page"),
    re_path(r"day-old/take/$", views.day_old_stock, name="day_old_stock"),
    re_path(r"vending/$", views.vending_machine_page, name="vending_machine_page"),
    re_path(
        r"vending/(?P<pk>[0-9]+)/vend/$",
        views.vending_machine,
        name="vending_machine",
    ),
]
