# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180412_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
