# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_inventory_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='cards', to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='plush',
            field=models.ManyToManyField(blank=True, related_name='plush', to='shop.Item'),
        ),
    ]
