# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180416_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
