# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-18 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
