# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180418_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
