# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='items',
            field=models.ManyToManyField(related_name='items', to='shop.Inventory'),
        ),
    ]
