# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180419_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='closed',
        ),
    ]
