# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_trade_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='receiving_user',
        ),
    ]
