# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_trade_receiving_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
