# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_trade_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
