# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_inventory_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='shop.Inventory'),
        ),
    ]
