# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
