# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
