# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_topic_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
